# Generated by Django 3.0.7 on 2020-08-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polar', '0007_service_decs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apponitment',
        ),
    ]
