# Generated by Django 3.0.7 on 2020-08-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polar', '0008_delete_apponitment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_status',
        ),
        migrations.DeleteModel(
            name='Booking_paid',
        ),
    ]
