# Generated by Django 3.0.7 on 2020-08-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polar', '0010_apponitment_bookpaid_bookstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apponitment',
        ),
        migrations.DeleteModel(
            name='BookPaid',
        ),
        migrations.DeleteModel(
            name='BookStatus',
        ),
    ]
